/******************************
CPSC 4910 PROJECT DATABASE
CREATED BY: NOAH RIGSBY
TEACHER: ROGER VAN SCOY
GROUP 4
DESCRIPTION: THIS SECTION DROPS
THE TABLES FROM THE DATABASE.
******************************/
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE DBUSER;
DROP TABLE SPONSOR;
DROP TABLE DRIVER;
DROP TABLE ADMINISTRATOR;
DROP TABLE PURCHASE;
DROP TABLE APPLICATION;
DROP TABLE CATALOG;
DROP TABLE CATEGORIES;
DROP TABLE GOODBEHAVIORAPP;
DROP TABLE PRODUCTS;
DROP TABLE OPERATION;
DROP TABLE USERTYPE;
DROP TABLE AWARDED;
DROP TABLE CONTAINS;
DROP TABLE SELECTRULES;
DROP TABLE CREATES;
DROP TABLE SECUREDFOR;
DROP TABLE REVIEWS;
DROP TABLE QUALIFIESFOR;
DROP TABLE EMPLOYS;
DROP TABLE ASSIGNS;
DROP TABLE SWITCHES;
DROP TABLE OWNS;
DROP PROCEDURE drivername;
DROP PROCEDURE sponsorname;
DROP PROCEDURE adminname;
DROP PROCEDURE login;
DROP PROCEDURE namestatus;
DROP PROCEDURE IDstatus;
DROP TABLE OLDPRICES;
DROP TABLE OLDSTATUS;
DROP TABLE OLDADMIN;
SET FOREIGN_KEY_CHECKS=1;
