/*****************************************
CPSC 4910 PROJECT DATABASE
CREATED BY: NOAH RIGSBY
TEACHER: ROGER VAN SCOY
GROUP 4
DESCRIPTION: THIS SECTION LETS THE USER
VIEW THE POPULATED TABLES IN THE DATABASE.
*****************************************/
SELECT * FROM GOODBEHAVIORAPP;
SELECT * FROM PRODUCTS;
SELECT * FROM DBUSER;
SELECT * FROM SPONSOR;
SELECT * FROM DRIVER;
SELECT * FROM ADMINISTRATOR;
SELECT * FROM PURCHASE;
SELECT * FROM APPLICATION;
SELECT * FROM CATALOG;
SELECT * FROM CATEGORIES;
SELECT * FROM USERTYPE;
SELECT * FROM OPERATION;
SELECT * FROM AWARDED;
SELECT * FROM CONTAINS;
SELECT * FROM SELECTRULES;
SELECT * FROM CREATES;
SELECT * FROM SECUREDFOR;
SELECT * FROM REVIEWS;
SELECT * FROM QUALIFIESFOR;
SELECT * FROM EMPLOYS;
SELECT * FROM ASSIGNS;
SELECT * FROM SWITCHES;
SELECT * FROM OWNS;
